d::exception& e) {
        std::cout << "exception : " << e.what